### PR TITLE
Extractors cleanup

### PR DESCRIPTION
**Pull request by petroid**
Removed duplicate extractors with identical "grok_pattern"s.
There are some extractors with identical "title"s, but different "grok_pattern"s, namely:
2 x "User Reconfigured Virtual Machine" @ lines 298 & 1559,
2 x "VCENTER DCUI Login Process" @ lines 340 & 1587,
2 x "VCENTER LOGIN STATUS" @ lines 326 & 1573,
2 x "Virtual Machine State stop/start" @ lines 1474 & 1601.
Please clarify which copies should stay

### CODE REVIEW

**Review by dcecchino — COMMENTED** [review]
These may seem like they are duplicates, but they've been tested on individual messages. The grok will be replaced with regex, however removing these lines will impact the dashboards.

**Comment by dcecchino** [comment]
Reviewing the 2x user reconfigured , I'm using two different grok fields, one username, and ldap_username 
Removed 1 DCUI 
VCENTER LOGIN STATUS similar with username one has ldap other has just username
 Virtual Machine State stop/start also has ldap vs username

**Comment by dcecchino** [comment]
Okay thank you for your help, I've merged your pull request.

**Review by dcecchino — COMMENTED** [review]
final

**Comment by petroid** [comment]
Thanks and good luck with your development:)

**Pull request merged**
